name: divine
description: A social media app made with Flutter.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.17.0
  firebase_auth: ^4.7.2
  firebase_storage: ^11.2.5
  google_sign_in: ^6.1.4
  cloud_firestore: ^4.8.4
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  loading_overlay: ^0.3.0
  lottie: ^2.6.0
  google_fonts: ^4.0.0
  flutter_spinkit: ^5.2.0
  ionicons: ^0.2.2
  animate_do: any
  simple_gradient_text: 1.2.4
  uuid: ^3.0.7
  flutter_web_frame: ^1.0.0
  cached_network_image: ^3.2.3
  image_picker: ^1.0.2
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  image_cropper: ^5.0.0
  firebase_app_check: ^0.1.5+1
  animations: ^2.0.7
  story: ^0.8.0
  story_view: ^0.14.0
  timeago: ^3.5.0
  flutter_screenutil: ^5.8.4
  animated_text_kit: ^4.2.2
  perfect_freehand: ^1.0.4
  image_gallery_saver: ^2.0.3
  image: ^4.0.17
  align_positioned: ^3.0.0
  photo_view: ^0.14.0
  gradient_borders: ^1.0.0
  flutter_image_compress: ^2.0.4
  image_pixels: ^3.0.0
  url_launcher: ^6.1.12
  blurrycontainer: 1.0.2
  path: ^1.8.0
  path_provider: ^2.0.15
  font_awesome_flutter: ^10.5.0
  screenshot: ^3.0.0
  flutter_colorpicker: ^1.0.3
  extended_image: ^8.1.1
  image_editor: ^1.3.0
  colorfilter_generator: ^0.0.8
  hand_signature: ^3.0.1
  fluttertoast: ^8.2.2
  camera: ^0.10.5+2
  video_player: 2.7.0
  photo_manager: ^3.0.0-dev.2
  oktoast: ^3.3.1
  transparent_image: ^2.0.1
  video_thumbnail: ^0.5.3
  fraction: ^5.0.1
  ffmpeg_kit_flutter_min: ^5.1.0
  matrix2d: ^1.0.4
  file_picker: ^5.3.3
  audioplayers: ^5.1.0
  flutter_nude_detector: ^0.0.4+1
  top_snackbar_flutter: ^3.1.0
  like_button: ^2.0.5
  shimmer: ^3.0.0
  expandable_text: ^2.3.0

dependency_overrides:
  photo_manager: ^3.0.0-dev.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/ml_models/

  fonts:
      - family: B612
        fonts:
          - asset: assets/fonts/B612-Regular.ttf

      - family: TitilliumWeb
        fonts:
          - asset: assets/fonts/TitilliumWeb-Regular.ttf

      - family: Varela
        fonts:
          - asset: assets/fonts/Varela-Regular.ttf

      - family: Vollkorn
        fonts:
          - asset: assets/fonts/Vollkorn-Regular.ttf

      - family: Rakkas
        fonts:
          - asset: assets/fonts/Rakkas-Regular.ttf

      - family: YatraOne
        fonts:
          - asset: assets/fonts/YatraOne-Regular.ttf

      - family: OldStandardTT
        fonts:
          - asset: assets/fonts/OldStandardTT-Italic.ttf

      - family: Neonderthaw
        fonts:
          - asset: assets/fonts/Neonderthaw-Regular.ttf

      - family: DancingScript
        fonts:
          - asset: assets/fonts/DancingScript-VariableFont_wght.ttf

      - family: SedgwickAve
        fonts:
          - asset: assets/fonts/SedgwickAve-Regular.ttf

      - family: IndieFlower
        fonts:
          - asset: assets/fonts/IndieFlower-Regular.ttf

      - family: Sacramento
        fonts:
          - asset: assets/fonts/Sacramento-Regular.ttf